config/routes.rb
Snarpur::Application.routes.draw do
  require "#{ RAILS_ROOT }/lib/util/route_util.rb"


  resources :entry_set_responses 
  get "person/:person_id/entry_set_responder_items(/:id)" => "people/entry_set_responder_items#index", :as => :person_entry_set_items

  resources :entry_values
  get 'entry_set_responses/:entry_set_response_id/section/:section_id' => 'entry_set_responses/sections#index', :as => :entry_set_response_section

  # Entry Field options
  match 'entry_fields/:id/entry_field_options' => 'entry_field_options#index', :via => :get 
  resources :entry_field_options, :only => [:destroy]

  resources :entry_sets do
    resources :sections  
  end

  resources :sections do  
    resources :entry_fields, :controller => 'sections/entry_fields'  
    resources :sections_entry_fields, :controller => 'sections/sections_entry_fields' 
  end
  match 'sections/:section_id/sections_entry_fields' => 'sections/sections_entry_fields#update', :via => :put
  resources :entry_fields
  resources :section_entry_fields, :only => [:destroy]
  


  mount Surveyor::Engine => "/surveys", :as => "surveyor"

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "invitation/edit" => 'devise/invitations#edit', :as => :accept_user_invitation
    put "invitation/update" => 'devise/invitations#update', :as => :user_confirmation
    get 'users', :to => 'users#show', :as => :user_root # Rails 3

  end

  match 'user/login_as/:id' => 'devise/switch_users#login_as', :as => :login_as, :via => :get
  match 'user/logout_as/:id' => 'devise/switch_users#logout_as', :as => :logout_as, :via => :get

  namespace :admin do
    resources :users
  end

  resources :users
  resources :people do
    resources :address, :only => [:index]
  end
  resources :people, :path => 'caretaker', :as => :caretaker do
    resources :people,:controller => "people/caretaker", :path => "subjects", :as => :subjects
  end
  
  resources :inverse_relations

  resources :relationships

  resources :responder_items do
    resources :people  
  end

  resources :people do
    resources :responder_items, :controller => 'people/responder_items'
  end


  resources :survey_responses, :path => 'responder_items/responses', :module => "responder_items", :only => [:index] do
    member do 
      get "column(/norm_reference/:norm_reference_id)" => "survey_responses#column"
      get "column(/norm_reference/:norm_reference_id/:column_metrics)" => "survey_responses#column"
      get "column(/:column_metrics)" => "survey_responses#column"
      get "question_group/:question_group_name" => 'survey_responses#question_group'
    end
  end




  resources :people, :as => 'subject' do
    resources :responder_items
  end
  

  #REFACTOR: change match to memeber
  resources :pre_registrations
  match "pre_registrations/:id(/step/:step_no)" => 'pre_registrations#show',:defaults => {:step_no => 1}, :via => :get, :as => :pre_registration_step
  match "pre_registrations/:id(/step/:step_no)" => 'pre_registrations#update',:defaults => {:step_no => 1}, :via => :put
  #REFACTOR: change match to memeber
  resources :responder_items, :path => 'invitation_items', :as => :invitation_items , :controller => "invitation_items" 
  

  match "invitation_items/:id/invite/:type/step/:step_no" => 'invitation_items#show',:defaults => {:step_no => 1,:type => "guardian"}, :via => :get, :as => :invitation_item_step
  match "invitation_items/invite/:type/step/:step_no" => 'invitation_items#create',:defaults => {:step_no => 1, :type => "guardian"}, :via => :post
  match "invitation_items/:id/invite/:type/step/:step_no" => 'invitation_items#update',:defaults => {:step_no => 1,:type => "guardian"}, :via => :put


  match 'all_surveys' => 'surveyor#index', :via => :get
  match 'people/:subject_id/responder_items/responses/:survey_id' => 'responder_items#responses', :via => :get
  match 'people/:subject_id/responder_items/responses/:respondent_id/:survey_id' => 'responder_items#responses', :via => :get
  match 'people/:subject_id/responder_items/survey/:survey_id' => 'responder_items#survey', :via => :get, :as => :survey
  # match 'responder_items/:id/responses/question_group/:question_group_name' => 'responder_items/survey_responses#question_group', :via => :get

  match 'people/:subject_id/history' => 'people#history'
  match 'people/:subject_id/information' => 'people#information'
  match 'people/:id/image_upload' => 'people#image_upload', :via => :put , :as => :image_upload
  
  
  post "sign_up/user", :to => 'sign_up#create'

  get "pages/error_401"
  get "pages/help"
  get "pages/landing"
  get "pages/browser_update"

  get "national_registers/:kennitala" => 'national_registers#lookup', :as => :lookup
  get "national_registers/family/:kennitala" => 'national_registers#family', :as => :family

  #REFACTOR: Try to pass this logic to Devise GEM
  root :to => 'application#index', constraints: lambda { |r| r.env["warden"].authenticate? }
  root :to => 'pages#landing'

end

app/models/responder_item.rb
class ResponderItem < ActiveRecord::Base
  belongs_to :person
  belongs_to :respondent, :class_name => "Person"
  belongs_to :caretaker, :class_name => "Person"
  belongs_to :subject, :class_name => "Person"
  belongs_to :survey
  belongs_to :response_set
  belongs_to :entry_set_response

  delegate :response_to_chart, :to => :response_set
  delegate :group_result, :to => :response_set
  delegate :access_code, :to => :response_set, :prefix => true
  delegate :full_name, :to => :subject, :prefix => true
  delegate :full_name, :to => :respondent, :prefix => true

  before_save :set_response_set, :if => :is_uncompleted_survey?
  after_save :send_respondent_invitation, :if => :invite_respondent_user

  scope :overdue, where("deadline < ? AND completed IS NULL", Time.zone.now)

  scope :uncompleted, where("deadline >= ? AND completed IS NULL", DateTime.now.at_midnight)
  scope :recently_completed, where("completed IS NOT NULL")
  scope :completed, where("completed IS NOT NULL")
  scope :surveys, where("survey_id IS NOT NULL").joins(:survey).select("surveys.access_code, responder_items.*")
  scope :surveys_by_id, lambda {|survey_id| where("survey_id = ?", survey_id).joins(:survey).select("surveys.access_code, responder_items.*")}
  scope :registrations, where("registration_identifier IS NOT NULL").order(:id)
  scope :entry_request, where("entry_set_response_id IS NOT NULL")
  scope :surveys_by_group, ResponderItem.surveys.order('survey_id')
  scope :by_respondent, lambda {|respondent_id| where("respondent_id = ?", respondent_id)}
  scope :by_subject, lambda {|subject_id| where(:subject_id => subject_id)}
  scope :entry_set_responses, where("entry_set_response_id IS NOT NULL")
  scope :subject_ids, select(:subject_id).uniq
  scope :order_by_complete_date, order("completed DESC, deadline ASC")

  accepts_nested_attributes_for :respondent, :subject, :entry_set_response

  attr_writer :current_user
  attr_accessor :invite_respondent_user, :subject_as_respondent

  
  attr_accessible :registration_identifier, :id, :caretaker_id, :deadline, :completed, 
                  :complete_item, :respondent_id, :subject_id, :survey_id, :invite_respondent_user, 
                  :days_until_deadline,:subject_attributes, :respondent_attributes, :entry_set_response_attributes,
                  :subject_as_respondent
  
  validates_associated :respondent, :subject

  def self.new_patient_item(params,caretaker)
    ResponderItem.new(params.merge({:caretaker_id => caretaker.id}))
  end

  def self.to_line_chart(params)
    ResponseSet.to_line_chart(params[:survey_id], params[:respondent_id])
  end

  def access_code
    self.survey.nil? ? self.registration_identifier : self.survey.access_code
  end

  def item_type
    if !self.survey.nil?
      'survey'
    elsif !self.entry_set_response.nil?
      'entry_set'
    elsif !self.registration_identifier.nil?
      'pre_registration'
    end
  end

  def is_survey?
    !self.survey.nil?
  end

  def is_entry_set_response?
    !self.entry_set_response.nil?
  end

  def is_subject?
    !self.subject.nil?
  end

  def is_respondent?
    !self.respondent.nil?
  end

  def complete_item=(is_complete)
   if is_complete.to_i == 1 && self.completed.nil?
    write_attribute :completed, Time.zone.now
   end
  end

  def result
    self.response_set.result_to_chart
  end

  private
  def is_uncompleted_survey?
    (!self.survey_id.nil? && self.completed.nil?)
  end

  def send_respondent_invitation
    respondent.user_invite!(caretaker.user) if not respondent.nil? and not respondent.user_is_invited?
  end

  def set_response_set
    self.response_set=(ResponseSet.create(:survey_id => self.survey_id, :user_id => self.respondent.user.id))
  end
  
end

app/controllers/people/caretaker_controller.rb
class People::CaretakerController < ApplicationController
  before_filter :get_user
  load_and_authorize_resource :person, :parent => false
  respond_to :json

  
  def show
    @person = Person.find(params[:id])
    @responder_items = @person.responder_items.surveys
  end

  def history
    @person = Person.find(params[:subject_id])
  end

  def information
    @person = Person.find(params[:subject_id])
  end

  def upload
    @person = Person.find(params[:subject_id])
  end

  def update
    @person= Person.find(params[:id])
    @person.update_attributes(params[:subject])
  end
end

app/controllers/people/responder_items_controller.rb
require 'ostruct'
class People::ResponderItemsController < ApplicationController
  before_filter :create_responder_item, :only => [:new,:create]
  # authorize_resource
  respond_to :json

   def index
    by_concern = params.key?("concern") ? "by_#{params['concern']}" : "by_subject"
    @responder_items = ResponderItem.send by_concern, params[:person_id]
   
    @responder_items
    
    authorize!(:index, *(@responder_items.any? ? @responder_items : ResponderItem.new))
   end
end

app/controllers/responder_items/survey_responses_controller.rb
class ResponderItems::SurveyResponsesController < ActionController::Base
  
  def question_group

    @responses = ResponderItem.find(params[:id]).group_result(params[:question_group_name])
  end


  def column
    @chart = ResponderItem.find(params[:id]).response_to_chart(params.slice(:column_metrics,:norm_reference_id))
  end


end

app/controllers/responder_items_controller.rb
require 'ostruct'
class ResponderItemsController < ApplicationController
  before_filter :create_responder_item, :only => [:new,:create], :if => :logged_in?
  before_filter :set_role_to_respondent, :only => [:create], :if => :logged_in?
  before_filter :get_surveys, :only => [:survey] , :if => :logged_in?
  after_filter :add_subject_as_respondent, :only => [:create]
  load_and_authorize_resource :only => [:create]
  respond_to :json

  def index
    @person = Person.find(params[:subject_id])
    @responder_items = @person.responder_items.surveys
    authorize!(:survey, *(@responder_items.any? ? @responder_items : ResponderItem.new))
    @responder_items
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @chart = ResponderItem.find(params[:id]).response_to_chart(params.slice(:result_name))
  end

  def new
    @responder_item ||= ResponderItem.new

  end

  def create
    if @responder_item.save
      RequestNotice.request_survey(@responder_item).deliver
      render :json => @responder_item
    else
      respond_with @responder_item
    end
  end

  def edit
    @responder_item = ResponderItem.find(params[:id])
  end

  def update
     @responder_item = ResponderItem.find(params[:id])

    respond_to do |format|
      if @responder_item.update_attributes(params[:responder_item])
        format.html { redirect_to(@current_user) }
      else
        format.html { render :action => "edit" }
      end
    end

  end
  
  #REFACTOR: Move to SurveyResponsesController
  def responses 
    @chart = ResponderItem.to_line_chart(params)
    respond_to do |format|
      format.html
      format.json {render "show"}
    end
  end

  #REFACTOR: Move to SurveyResponsesController
  def survey
    @responder_items
    authorize!(:survey, *(!@responder_items.nil? && @responder_items.any? ? @responder_items : ResponderItem.new)) 
    @responder_items
  end
  
  private
  def create_responder_item
    params_without_root = params[:responder_item] || params
    attr_ok = ResponderItem._accessible_attributes[:default].to_a
    args = params_without_root.slice(*attr_ok)
    @responder_item = ResponderItem.new_patient_item(args,current_user.person)
  end

  def get_surveys
    @person = Person.find(params[:subject_id])
    @responder_items = @person.responder_items.surveys_by_id(params[:survey_id])
  end

  def is_caretaker?(responder_item)
    (@current_user.person_id ==  @responder_item.caretaker_id)
  end

  def is_subject_registration?(responder_item)
    (responder_item.registration_identifier.present? and responder_item.registration_identifier ==  "subject_registration")
  end

  def is_guardian_registration?(responder_item)
    (responder_item.registration_identifier.present? and responder_item.registration_identifier ==  "respondent_registration")
  end

  def add_subject_as_respondent
    if is_caretaker?(@responder_item) and is_subject_registration?(@responder_item)
      @responder_item.update_attributes(:respondent_id => @responder_item.subject_id,:invite_respondent_user => true) 
    end
  end

  def set_role_to_respondent
    if is_subject_registration?(@responder_item)
      @responder_item.subject.user.set_role("respondent")
    else
      if is_guardian_registration?(@responder_item)
        @responder_item.respondent.user.set_role("respondent")
      end
    end
  end

  def send_email_notification
    RequestNotice.request_survey(@responder_item).deliver
  end

end

app/helpers/responder_items_helper.rb
module ResponderItemsHelper
 
  def deadline_or_completed_date(item)
    date = item.completed ? item.completed : item.deadline
    before_or_after_today(date)
  end
  
  def user_partial_path(path)
    partial = @current_user.roles.first.name
    "responder_items/#{partial}/#{path}"
  end

  def responder_item_partial_for(person,responder_items,path=nil)
      path = path.nil? ? "/" : "/#{path}/"
      render :partial => "responder_items/#{person.role}#{path}items", :collection => responder_items, :as => :item
  end

  def responder_item_index_partial
    partial = @current_user.roles.first.name
    if @person.nil?
      "responder_items/#{partial}/index"
    else
      "responder_items/#{partial}/patient_index"
    end
  end
  
end

app/views/responder_items/caretaker/_index.html.haml
=content_for :content_title, t('terms.client', :count => 2)

/ =content_for :state_overview do
/   =render "shared/state_overview"

=content_for :javascript_initializations do
  =render "/responder_items/shared/users_datatable"

.row
  .col-lg-12
    %section{:class=>"panel"}
      .panel-heading.clearfix
        .btn-group.pull-right
          %button{:type=>"button", :class=>"btn btn-info dropdown-toggle", :data=>{:toggle=>"dropdown"}}
            %i{:class=>"fa fa-plus"}
            %i{:class=>"fa fa-user"}
            = t('actions.invite_clients')              
            %span{:class=>"caret"}
          %ul{:class=>"dropdown-menu", :role=>"menu"}
            %li
              =link_to t('actions.minor'), "/#invitation_items/invite/guardian"
            %li
              =link_to t('actions.adult'), "/#invitation_items/invite/subject"
      .panel-body
        .adv-table
          #users_wrapper{:class=>"dataTables_wrapper form-inline"}
            %table{:id=>"users", :class=>"display table table-bordered table-striped dataTable",:role=>"grid"}
              %thead
                %tr
                  %th
                    = t('person.name')
                  %th
                    = t('views.users.content.uncompleted_requests')
                  %th
                    = t('views.users.content.completed_requests')
                  %th
                    = t('views.users.content.login_as')
              %tbody
                -@patients.each do |p|
                  %tr
                    %td
                      = link_to p.full_name, "/#timeline#{subject_path(p)}"
                    %td
                      - u = p.responder_items.surveys.uncompleted.count
                      -unless u.zero?
                        %span{:class=>"badge bg-warning"}
                          = u
                    %td
                      - o = p.responder_items.surveys.overdue.count
                      - unless o.zero?
                        %span{:class=>"badge bg-important"}
                          = o
                    %td
                      -unless p.list_respondents.size.zero?
                        %a{:href => login_as_path(p.list_respondents.first)}
                          %i{:class=>"fa fa-user"}
                          %i{:class=>"fa fa-share"}      

app/views/responder_items/caretaker/_index.html_OLD.haml
=content_for :content_title, t('terms.client', :count => 2)
=content_for :subject_content do
  =render "shared/content_title"

%ul{:class => 'reset toolbar'}
  %li{:class => 'left'}
    %form
      %input{:type => 'text', :id => 'patient-search', :class => 'search-input'}

  %li{:class => 'right'}
    %div{:class => 'dropdown btn-group'}
      =link_to content_tag(:span, '', :class => 'icon-user-add' ) + t('actions.invite_clients'), "#", :class => 'dropdown-toggle button prime', :data => {:toggle=>"dropdown"}
      %ul{:class => 'dropdown-menu'}
        %li
          =link_to t('actions.minor'), "/#invitation_items/invite/guardian"
        %li
          =link_to t('actions.adult'), "/#invitation_items/invite/subject"


%table.table
  %thead
    %tr
      %th
        = t('person.name')
      %th{:class => 'small'}
        = t('views.users.content.uncompleted_requests')
      %th{:class => 'small'}
        = t('views.users.content.completed_requests')
      %th{:class => 'small'}
        = t('views.users.content.login_as')
  %tbody
    -@patients.each do |p|
      %tr
        %td
          = link_to p.full_name, subject_path(p)
        %td{:class => 'thin center incomplete'}
          - u = p.responder_items.surveys.uncompleted.count
          -unless u.zero?
            %span
              = u
        %td{:class => 'thin center overdue'}
          - o = p.responder_items.surveys.overdue.count
          - unless o.zero?
            %span
              = o
        %td{:class => 'center login'}
          -unless p.list_respondents.size.zero?
            %a{:href => login_as_path(p.list_respondents.first)}
              %span.icon-user
              %span.icon-share-alt      

app/views/responder_items/caretaker/_item.html.haml
%tr{:class => item.item_type}
  %td= link_to item.subject.full_name, person_path(item.subject)
  %td= t("surveys.#{item.access_code}.name")
  %td="#{item.respondent.firstname} #{item.respondent.lastname}"
  %td=l item.created_at, :format => :short
  %td=deadline_or_completed_date(item)

app/views/responder_items/caretaker/_items.html.haml
%h2= t("responder_item.status.#{item[:name]}.header").capitalize
%div{:class =>"#{item[:name]}"}
  %table
    %tr
      %th Sjúklingur
      %th Tegund
      %th Svarandi
      %th Beiðni send dags.
      %th= t("responder_item.status.#{item[:name]}.column").capitalize
    = render :partial => user_partial_path("item"), :collection => item[:items]

app/views/responder_items/caretaker/_patient_index.html.haml
=render "shared/timeline/canvas", :responses => @responder_items

app/views/responder_items/caretaker/_show.html.haml
// = opt = ResponderItem.to_chart(params)
/ #lineContainer
/ :javascript
/ 	var lineOptions = #{opt.to_json}
/ 	console.log(lineOptions)
/ 	$(document).ready(function(){
/ 		new Highcharts.Chart(lineOptions[0])
/ 	});